//! Opaque credential generation and constant-time comparison. No dependency on `tauri` — shared
//! by the app binary (issues credentials) and the companion binary (never sees this module at
//! all; it only ever holds the credential value it was handed).

use rand::RngCore;

/// A random, hex-encoded token with `byte_len` bytes of entropy (32 bytes = 256 bits by default
/// call sites in this crate) — long enough that guessing is infeasible, short enough to be
/// copy-pasted into an MCP host config without incident.
pub fn generate_token(byte_len: usize) -> String {
    let mut bytes = vec![0u8; byte_len];
    rand::thread_rng().fill_bytes(&mut bytes);
    hex_encode(&bytes)
}

fn hex_encode(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

/// Constant-time comparison (for equal-length inputs) so a rejected credential guess cannot be
/// timed byte-by-byte against the real secret. Deliberately does not short-circuit on the first
/// differing byte. A length mismatch returns `false` immediately: on this local-IPC threat model
/// (secrets are fixed-length, generated by `generate_token`) leaking "the length didn't even
/// match" carries no meaningful signal.
pub fn secrets_match(a: &str, b: &str) -> bool {
    let (a, b) = (a.as_bytes(), b.as_bytes());
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_tokens_are_hex_and_have_the_requested_entropy() {
        let token = generate_token(32);
        assert_eq!(token.len(), 64);
        assert!(token.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn generated_tokens_are_not_trivially_repeated() {
        let a = generate_token(32);
        let b = generate_token(32);
        assert_ne!(a, b);
    }

    #[test]
    fn secrets_match_accepts_identical_values() {
        assert!(secrets_match("abc123", "abc123"));
    }

    #[test]
    fn secrets_match_rejects_different_values_and_different_lengths() {
        assert!(!secrets_match("abc123", "abc124"));
        assert!(!secrets_match("abc123", "abc12"));
        assert!(!secrets_match("", "a"));
    }
}
